# Generated by Django 4.2.11 on 2024-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_remove_sery_id_sery_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(to='poster.genre'),
        ),
    ]
