# Generated by Django 4.2.11 on 2024-04-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_genre_anime_poster_anime_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.FileField(upload_to='', verbose_name='Постер'),
        ),
    ]
