# Generated by Django 4.2.11 on 2024-05-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0008_roles_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
